### PR TITLE
add gEDA pcb footprint generator

### PR DESCRIPTION
**Pull request by cuvoodoo**
this only adds gEDA pcb footprint generator since pcb is only for board layout.
board definition output could be added.
symbol and library support are out of scope.

please add this output support in the documentation.

### CODE REVIEW

**Comment by UncleRus** [comment]
That's pretty cool!

**Comment by shamil-ru** [comment]
Dear @cuvoodoo,

Thanks a lot for such a valuable pull request.

But may I ask you to make some renaming because "pcb" is too common and may cause misunderstanding.

I would ask you to rename:

`pcb-generator` -> `geda-generator`
`PcbGenerator` -> `GedaGenerator`
`pcb` -> `geda`

And I will issue the new release after this update due to its importance.

**Comment by cuvoodoo** [comment]
Since gEDA is more of a collection of independent programs (e.g. not really a suite), I wouldn't rename it GedaGenerator since gEDA is more than just pcb (e.g. gschem is the schematic counterpart). GedaPcbGenerator would be fine though.
If you think this generator is that important, I would wait a bit though. I am currently writing the symbol generator for gEDA gschem. I could name it GedaGschemGenerator to match this nomenclature, but if you prefer I can combine it with GedaPcbGenerator into GedaGenerator which would have Gschem symbols and pcb footprints outputs in one generator (since they are often used together). How does that sound?

After these two generators I will write a footprint generator for pcb-rnd. pcb-rnd is a fork of pcb, which (will) support more features than pcb (e.g. non-round through hole, buried vias, keep-out for courtyard, notes for fabrication layer).
I don't know if pcb-rnd is still considered as part of gEDA, since it is actually also compatible with other software (KiCAD, Eagle, ...) and not only gschem.
I can ask the developer team to know if they wish to have it independent, or also include this generator in the gEDA generator.
In the later case you would also have to wait until I finished writing this before the release. I don't think this will take too long though (a couple of weeks).

In any case, I would still make different branches for each of the generator and make pull request, but just so people can actually test it and let me know if there are issues. I only tried the generators for a small test project and can't test all cases/details.

**Comment by shamil-ru** [comment]
My opinion the combined GedaGenerator with both PCB and schematic parts generation would be the best option. There is no any problem for me to wait.
Also, I do not see the problem to include this patch to the master branch. This generator seems to not affect other functionality so anybody could test it without compiling it from GitHub.

Your contributions are much appreciated. People like you inspire me to continue the project. I hope to find the power and to be back :-)

**Comment by cuvoodoo** [comment]
I've renamed the generator to GedaPcbGenerator as discussed.
Feel free to merge it for people who would like to test it without having to compile it themselves (set output to "geda/pcb"), but consider the names and output structure only as temporary until I've merged the pcb generator to the common gEDA generator.

**Pull request merged**
